/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_chen_com_detecthandwriting_CheckActivity */

#ifndef _Included_example_chen_com_detecthandwriting_CheckActivity
#define _Included_example_chen_com_detecthandwriting_CheckActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_chen_com_detecthandwriting_CheckActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_example_chen_com_detecthandwriting_CheckActivity_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     example_chen_com_detecthandwriting_CheckActivity
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_example_chen_com_detecthandwriting_CheckActivity_gray
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
